# Generated by Django 5.1.7 on 2025-03-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_enhancer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('prompt', models.TextField(blank=True, null=True)),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='processed/')),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
